### ISSUE TITLE
Not clear that cloudflare was a prereq 

### ISSUE THREAD

**Issue by kcirtapfromspace** [l-mds/local-data-stack#1]
Not clear that cloudflare was a prereq. 

What kind of service is being used and what type of API key is needed

[7/11] cloudflare_api_key (<<your-secret-key>>): 
  [8/11] cloudflare_email (<<your-e-mail>>):

**Comment by geoHeil** [comment]
This template consists of building blocks. 

- the base stack for data handling where localhost:<<some port>> is exposing services either directly or via docker on the (local) host
- https://github.com/l-mds/local-data-stack/tree/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/prototyping/proxy as an example for how you may want to host/expose these more properly via DNS

if you choose to **not** use such an exposure - you do not need them.

The particular key is the lets-encrypt DNS challenge for Cloudflare.

**Comment by geoHeil** [comment]
closing now as no follow up was sent
